/* sparse.h : Impala interface file generated by impala */
#ifndef SPARSE_H
#define SPARSE_H

#ifdef __cplusplus
extern "C" {
#endif

struct CSR {
    unsigned int N;
    unsigned int M;
    unsigned int nnz;
    float* values;
    unsigned int* cols;
    unsigned int* row_index;
};

unsigned int get_nnz(struct CSR const* cst);

#ifdef __cplusplus
}
#endif

#endif /* SPARSE_H */

